name: Cache Monitoring on Prod

on:
  push:
    branches:
      - master

jobs:
  validate-cache-headers:
      runs-on: ubuntu-24.04
      timeout-minutes: 10
      steps:
        - uses: actions/checkout@v4
        
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
            
        - name: Install dependencies
          run: npm ci
          
        - name: Install Playwright with browsers
          run: npx playwright install --with-deps chromium
          
        - name: Run Playwright test
          run: npx playwright test tests/playwright-tests/cache-checker.spec.ts
          
        - name: Upload results
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: cache-validation-results
            path: |
              results.json
              playwright-report/
              test-logs.txt  # Optional: Include the log file in artifacts for download/archive
        
        # - name: FINAL VALIDATION & SUMMARY TEST REPORT
        #   if: always()
        #   run: |
        #     if [ -f test-logs.txt ]; then
        #       echo "===== Playwright Test Logs ====="
        #       cat test-logs.txt
        #       echo "================================"
        #     else
        #       echo "No test logs found."
        #     fi
